In [1]:
#### Ejercicio 1 ####
import numpy as np
def area_circulo(a):
    area = np.pi * (a)**2
    return area

radio = int(input("Ingresa un radio: "))
area = area_circulo(radio)
print(area)

#### Ejercicio 2, a) ####
lista = [1,2,3,4,5]
def suma_elementos(l):
    total = 0
    for i in lista:
        print(i)
    for i in lista:
        total += i
    return total 

res = suma_elementos(lista)
print(res)


#### Ejercicio 2, b) Implementa una función que calcule la suma de la lista empleando un bucle for o while. Utiliza la notación matemática: ####
#### Ejercicio 2, c) Desarrolla una función f(n) que calcule la suma de los primeros n valores enteros positivos. Compara el resultado con la fórmula analítica:

def f(n):
    suma = 0
    for i in range(0, n+1):
        suma += i
    return suma

print(f(10))

#### Ejercicio 3 #### 
# a) Crea una función que calcule el producto de todos los elementos en la lista
numeros = [1, 2, 3, 4, 5]
def producto_lista(a):
    producto = 1
    for i in numeros:
        print(i)
        producto *= i
    return producto
print(producto_lista(numeros))

# b) Desarrolla una función que calcule el producto de los primeros n enteros positivos (factorial de n). Compara el resultado con la función math.factorial().
from math import factorial
import math as mt
def funcfactorial(a):
    factorial = 1
    for i in range(1, a+1):
        factorial *= i
    return factorial

if funcfactorial(10) == mt.factorial(10):
    print(True)
else:
    print(False)


#### Ejercicio 3 ####
#Utilizando NumPy, realiza las siguientes operaciones:
#a) Crea una matriz 3x3 y escribe una función que imprima todos sus elementos.
#matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#b) Imprime los elementos de la matriz en orden inverso (de abajo hacia arriba y de derecha a izquierda).
#c) Extrae la segunda columna de la matriz y conviértela en un vector. Imprime este vector.
matriz = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
def imprime_elementos(a):
    print(a)
imprime_elementos(matriz)

Ingresa un radio: 3
28.274333882308138
1
2
3
4
5
15
55
1
2
3
4
5
120
True
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
from math import factorial
import math as mt
def funcfactorial(a):
    factorial = 1
    for i in range(1, a+1):
        factorial *= i
    return factorial

if funcfactorial(10) == mt.factorial(10):
    print(True)
else:
    print(False)


True


In [4]:
numeros = [1, 2, 3, 4, 5]
def producto_lista(a):
    producto = 1
    for i in numeros:
        print(i)
        producto *= i
    return producto
print(producto_lista(numeros))

1
2
3
4
5
120


In [5]:
# b) Desarrolla una función que calcule el producto de los primeros n enteros positivos (factorial de n). Compara el resultado con la función math.factorial().
from math import factorial
import math as mt
def funcfactorial(a):
    factorial = 1
    for i in range(1, a+1):
        factorial *= i
    return factorial

if funcfactorial(10) == mt.factorial(10):
    print(True)
else:
    print(False)


True


In [6]:
#### Ejercicio 3 ####
#Utilizando NumPy, realiza las siguientes operaciones:
#a) Crea una matriz 3x3 y escribe una función que imprima todos sus elementos.
#matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#b) Imprime los elementos de la matriz en orden inverso (de abajo hacia arriba y de derecha a izquierda).
#c) Extrae la segunda columna de la matriz y conviértela en un vector. Imprime este vector.
matriz = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
def imprime_elementos(a):
    print(a)
imprime_elementos(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
