# Notación y Operaciones Matriciales en Ingeniería

## 1. Introducción a las Matrices
- Una matriz es un arreglo rectangular de elementos representado por un solo símbolo.
- Notación: $[A]$ representa la matriz, $a_{i,j}$ designa un elemento individual.
- Dimensiones: n × m (n filas, m columnas).

## 2. Tipos Especiales de Matrices
- **Vector renglón:** matriz 1 × m
- **Vector columna:** matriz n × 1
- **Matriz cuadrada:** n = m
- **Tipos especiales de matrices cuadradas:**
  ### **Simétrica:**

  a_ij = a_ji para todo i y j
    Ejemplo: 
    $$
    [A] = \begin{bmatrix}
    5 & 1 & 2 \\
    1 & 3 & 7 \\
    2 & 7 & 8
    \end{bmatrix}
    $$
  ### **Diagonal:** 
  todos los elementos fuera de la diagonal principal son cero
    Ejemplo:
    $$
    [A] = \begin{bmatrix}
    4 & 0 & 0 \\
    0 & 7 & 0 \\
    0 & 0 & 2
    \end{bmatrix}
    $$
  ### **Identidad:** 
  
  matriz diagonal con unos en la diagonal principal
    Ejemplo:
    $$
    [I] = \begin{bmatrix}
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & 1
    \end{bmatrix}
    $$
  ### **Triangular superior:** 
  
  todos los elementos por debajo de la diagonal principal son cero
    Ejemplo:
    $$
    [A] = \begin{bmatrix}
    3 & 2 & 1 \\
    0 & 5 & 4 \\
    0 & 0 & 6
    \end{bmatrix}
    $$
  ### **Triangular inferior:** 
  
  todos los elementos por arriba de la diagonal principal son cero
    Ejemplo:
    $$
    [A] = \begin{bmatrix}
    2 & 0 & 0 \\
    3 & 7 & 0 \\
    1 & 4 & 9
    \end{bmatrix}
    $$
  ###  **Matriz a bandas (ej. tridiagonal):** 
  
  elementos no nulos solo en una banda centrada en la diagonal principal
    Ejemplo:
    $$
    [A] = \begin{bmatrix}
    1 & 2 & 0 \\
    4 & 5 & 6 \\
    0 & 7 & 8
    \end{bmatrix}
    $$

## 3. Operaciones Básicas con Matrices

### 3.1 Igualdad de Matrices
Dos matrices [A] y [B] son iguales si tienen las mismas dimensiones y todos sus elementos correspondientes son iguales.

Ejemplo:
$$
[A] = \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix} = [B] = \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
$$

### 3.2 Suma y Resta de Matrices
La suma y resta de matrices se realiza elemento por elemento. Las matrices deben tener las mismas dimensiones.

Ejemplo de suma:
$$
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix} + 
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix} = 
\begin{bmatrix}
1+5 & 2+6 \\
3+7 & 4+8
\end{bmatrix} = 
\begin{bmatrix}
6 & 8 \\
10 & 12
\end{bmatrix}
$$

Ejemplo de resta:
$$
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix} - 
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix} = 
\begin{bmatrix}
5-1 & 6-2 \\
7-3 & 8-4
\end{bmatrix} = 
\begin{bmatrix}
4 & 4 \\
4 & 4
\end{bmatrix}
$$

### 3.3 Multiplicación por Escalar
La multiplicación de una matriz por un escalar se realiza multiplicando cada elemento de la matriz por el escalar.

Ejemplo:
$$
3 \cdot \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix} = 
\begin{bmatrix}
3 \cdot 1 & 3 \cdot 2 \\
3 \cdot 3 & 3 \cdot 4
\end{bmatrix} = 
\begin{bmatrix}
3 & 6 \\
9 & 12
\end{bmatrix}
$$

### 3.4 Multiplicación de Matrices
La multiplicación de matrices [A] y [B] para obtener [C] se realiza de la siguiente manera:
- El número de columnas de [A] debe ser igual al número de filas de [B].
- El elemento c_ij de la matriz resultante [C] se obtiene multiplicando los elementos de la fila i de [A] por los elementos de la columna j de [B] y sumando los resultados.

Ejemplo:
$$
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix} \cdot 
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix} = 
\begin{bmatrix}
(1 \cdot 5 + 2 \cdot 7) & (1 \cdot 6 + 2 \cdot 8) \\
(3 \cdot 5 + 4 \cdot 7) & (3 \cdot 6 + 4 \cdot 8)
\end{bmatrix} = 
\begin{bmatrix}
19 & 22 \\
43 & 50
\end{bmatrix}
$$

Donde los elementos se puedes escribir como:

$$
c_{ij}= \sum_{k=1}^n a_{ik}\ b_{kj}
$$

Nota importante: La multiplicación de matrices no es conmutativa en general, es decir, [A][B] ≠ [B][A].



## 4. Propiedades de las Operaciones
- Conmutatividad de la suma: [A] + [B] = [B] + [A]
- Asociatividad de la suma: ([A] + [B]) + [C] = [A] + ([B] + [C])


In [10]:
import numpy as np

## Matrices cero

In [11]:
# Ejemplo 1: Crear una matriz 2D de ceros
filas = 3
columnas = 4
matriz_2d = np.zeros((filas, columnas))
print("Matriz 2D de ceros:")
print(matriz_2d)
print("\nTipo de datos:", matriz_2d.dtype)

Matriz 2D de ceros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Tipo de datos: float64


In [12]:
# Ejemplo 2: Crear una matriz 1D (vector) de ceros
longitud = 5
vector = np.zeros(longitud)
print("\nVector de ceros:")
print(vector)


Vector de ceros:
[0. 0. 0. 0. 0.]


In [13]:
# Ejemplo 3: Especificar el tipo de datos
matriz_enteros = np.zeros((2, 2), dtype=int)
print("\nMatriz de ceros (enteros):")
print(matriz_enteros)


Matriz de ceros (enteros):
[[0 0]
 [0 0]]


In [14]:
# Ejemplo 4: Crear una matriz 3D de ceros
profundidad = 2
altura = 3
anchura = 4
matriz_3d = np.zeros((profundidad, altura, anchura))
print("\nMatriz 3D de ceros:")
print(matriz_3d)


Matriz 3D de ceros:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [15]:
# Ejemplo 5: Crear una matriz de ceros con la misma forma que otra matriz
otra_matriz = np.array([[1, 2, 3], [4, 5, 6]])
matriz_ceros_misma_forma = np.zeros_like(otra_matriz)
print("\nMatriz de ceros con la misma forma que otra matriz:")
print(matriz_ceros_misma_forma)


Matriz de ceros con la misma forma que otra matriz:
[[0 0 0]
 [0 0 0]]


### Matrices diagionales

In [23]:
# Ejemplo 1: Crear una matriz diagonal a partir de un vector
vector = [1, 2, 3, 4]
matriz_diagonal = np.diag(vector)
print("Matriz diagonal a partir de un vector:")
print(matriz_diagonal)

Matriz diagonal a partir de un vector:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [18]:
# Ejemplo 2: Extraer la diagonal de una matriz existente
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
diagonal = np.diag(matriz)
print("\nDiagonal extraída de una matriz:")
print(diagonal)


Diagonal extraída de una matriz:
[1 5 9]


In [24]:
# Ejemplo 3: Crear una matriz identidad
n = 4
matriz_identidad = np.eye(n)
print("\nMatriz identidad:")
print(matriz_identidad)


Matriz identidad:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
# Ejemplo 4: Crear una matriz con valores específicos en la diagonal
n = 4  # tamaño de la matriz
valor_diagonal = 5
matriz_diagonal_valor = np.eye(n) * valor_diagonal
print("\nMatriz diagonal con valor específico:")
print(matriz_diagonal_valor)


Matriz diagonal con valor específico:
[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


In [21]:
# Ejemplo 5: Crear una matriz diagonal con offset
vector = [1, 2, 3, 4]
k = 1  # offset positivo (por encima de la diagonal principal)
matriz_diagonal_offset = np.diag(vector, k)
print("\nMatriz diagonal con offset positivo:")
print(matriz_diagonal_offset)

k = -1  # offset negativo (por debajo de la diagonal principal)
matriz_diagonal_offset_neg = np.diag(vector, k)
print("\nMatriz diagonal con offset negativo:")
print(matriz_diagonal_offset_neg)


Matriz diagonal con offset positivo:
[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]

Matriz diagonal con offset negativo:
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [20]:
# Ejemplo 6: Crear una matriz diagonal a partir de una función
n = 5
matriz_diagonal_func = np.diag([i*2 for i in range(1, n+1)])
print("\nMatriz diagonal a partir de una función:")
print(matriz_diagonal_func)


Matriz diagonal a partir de una función:
[[ 2  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  6  0  0]
 [ 0  0  0  8  0]
 [ 0  0  0  0 10]]


## Multiplicar Matrices 
### Ejemplo con np.dot()

In [1]:
import numpy as np

def multiplicar_matrices(A, B):
    """
    Multiplica dos matrices A y B.
    
    Args:
    A (list of lists): Primera matriz
    B (list of lists): Segunda matriz
    
    Returns:
    list of lists: Resultado de la multiplicación de A y B
    """
    # Convertir las listas de Python a arrays de NumPy
    A = np.array(A)
    B = np.array(B)
    
    # Verificar si las matrices pueden ser multiplicadas
    if A.shape[1] != B.shape[0]:
        raise ValueError("El número de columnas de A debe ser igual al número de filas de B")
    
    # Realizar la multiplicación
    C = np.dot(A, B)
    
    # Convertir el resultado de vuelta a una lista de listas
    return C.tolist()

# Ejemplo de uso
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]

resultado = multiplicar_matrices(A, B)

print("Matriz A:")
for fila in A:
    print(fila)

print("\nMatriz B:")
for fila in B:
    print(fila)

print("\nResultado de A * B:")
for fila in resultado:
    print(fila)

Matriz A:
[1, 2]
[3, 4]

Matriz B:
[5, 6]
[7, 8]

Resultado de A * B:
[19, 22]
[43, 50]


### Ejemplo de manera explícita

In [25]:
def multiplicar_matrices(A, B):
    """
    Multiplica dos matrices A y B de manera explícita.
    
    Args:
    A (list of lists): Primera matriz
    B (list of lists): Segunda matriz
    
    Returns:
    list of lists: Resultado de la multiplicación de A y B
    """
    # Verificar si las matrices pueden ser multiplicadas
    if len(A[0]) != len(B):
        raise ValueError("El número de columnas de A debe ser igual al número de filas de B")
    
    # Obtener dimensiones
    filas_A = len(A)
    columnas_A = len(A[0])
    columnas_B = len(B[0])
    
    # Crear matriz resultado inicializada con ceros
    C = [[0 for _ in range(columnas_B)] for _ in range(filas_A)]
    
    # Realizar la multiplicación
    for i in range(filas_A):
        for j in range(columnas_B):
            for k in range(columnas_A):
                C[i][j] += A[i][k] * B[k][j]
    
    return C

# Ejemplo de uso
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]

resultado = multiplicar_matrices(A, B)

print("Matriz A:")
for fila in A:
    print(fila)

print("\nMatriz B:")
for fila in B:
    print(fila)

print("\nResultado de A * B:")
for fila in resultado:
    print(fila)

# Verificación paso a paso
print("\nVerificación paso a paso:")
print(f"C[0][0] = (A[0][0] * B[0][0]) + (A[0][1] * B[1][0]) = ({A[0][0]} * {B[0][0]}) + ({A[0][1]} * {B[1][0]}) = {resultado[0][0]}")
print(f"C[0][1] = (A[0][0] * B[0][1]) + (A[0][1] * B[1][1]) = ({A[0][0]} * {B[0][1]}) + ({A[0][1]} * {B[1][1]}) = {resultado[0][1]}")
print(f"C[1][0] = (A[1][0] * B[0][0]) + (A[1][1] * B[1][0]) = ({A[1][0]} * {B[0][0]}) + ({A[1][1]} * {B[1][0]}) = {resultado[1][0]}")
print(f"C[1][1] = (A[1][0] * B[0][1]) + (A[1][1] * B[1][1]) = ({A[1][0]} * {B[0][1]}) + ({A[1][1]} * {B[1][1]}) = {resultado[1][1]}")

Matriz A:
[1, 2]
[3, 4]

Matriz B:
[5, 6]
[7, 8]

Resultado de A * B:
[19, 22]
[43, 50]

Verificación paso a paso:
C[0][0] = (A[0][0] * B[0][0]) + (A[0][1] * B[1][0]) = (1 * 5) + (2 * 7) = 19
C[0][1] = (A[0][0] * B[0][1]) + (A[0][1] * B[1][1]) = (1 * 6) + (2 * 8) = 22
C[1][0] = (A[1][0] * B[0][0]) + (A[1][1] * B[1][0]) = (3 * 5) + (4 * 7) = 43
C[1][1] = (A[1][0] * B[0][1]) + (A[1][1] * B[1][1]) = (3 * 6) + (4 * 8) = 50
