# Guía de Álgebra Lineal con NumPy

## 1. Introducción

- NumPy es una librería fundamental en Python para cálculos numéricos y científicos. 

- Su submódulo `numpy.linalg` ofrece potentes herramientas para operaciones de álgebra lineal.

[enlace a linalg de Numpy](https://numpy.org/doc/stable/reference/routines.linalg.html)

## 2. Instalación

```bash
# sin conda 
pip install numpy
#con conda instalado
conda install numpy
```

## 3. Importación


In [62]:
import numpy as np

## 4. Operaciones Básicas

### 4.1. Producto Punto 

$$\mathbf{a} \cdot \mathbf{b} = \sum_{i=1}^n a_i b_i$$


In [64]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
producto_punto = np.dot(a, b) # aqui implementamos el producto punto
print (producto_punto)
# (1*4 +2*5 + 3*6) = 32

32


### 4.2. Producto de Matrices (producto punto)

$$(\mathbf{AB})_{ij} = \sum_{k=1}^n A_{ik}B_{kj}$$

In [34]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
producto_matrices = np.matmul(A, B)

print(A)
print(B)

print(producto_matrices)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [65]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
producto_punto = np.dot(A, B)
print (producto_punto)

[[19 22]
 [43 50]]


In [12]:
A@B

array([[19, 22],
       [43, 50]])

**Ejercicio**

1. Construya un función (def) para calcular el producto punto de dos matrices

### 4.3 Producto Matrices por elemento

El resultado es una nueva matriz C donde el elemento C[i,j] se calcula como la suma de los productos de los elementos de la fila i de A con los elementos correspondientes de la columna j de B.

$$
(A \circ B)_{ij} = A_{ij}B_{ij}
$$

In [38]:
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [13]:
A*B

array([[ 5, 12],
       [21, 32]])

In [14]:
np.multiply(A,B)

array([[ 5, 12],
       [21, 32]])

### 4.3. Determinante

**Para una matriz 2x2:**

$$\det \begin{pmatrix} a & b \\ c & d \end{pmatrix} = ad - bc$$

In [68]:
matriz = np.array([[1, 2], [3, 4]])
determinante = np.linalg.det(matriz)
print(determinante)
determinante.round(5)

-2.0000000000000004


-2.0

**Para una matriz 3x3:** 
$$
A = \begin{vmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{vmatrix}
$$

$$
\det(A) = a_{11}a_{22}a_{33} + a_{12}a_{23}a_{31} + a_{13}a_{21}a_{32} - a_{13}a_{22}a_{31} - a_{12}a_{21}a_{33} - a_{11}a_{23}a_{32}
$$


Ejemplo Numérico
Consideremos la matriz:
$$
A = \begin{vmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{vmatrix}
$$
Calculamos su determinante:
$$
\begin{align*}
\det(A) &= (1 \cdot 5 \cdot 9) + (2 \cdot 6 \cdot 7) + (3 \cdot 4 \cdot 8) \\
&- (3 \cdot 5 \cdot 7) - (2 \cdot 4 \cdot 9) - (1 \cdot 6 \cdot 8) \\
&= 45 + 84 + 96 - 105 - 72 - 48 \
&= 0
\end{align*}
$$

In [41]:
matriz = np.array([[1, 2, 3], [4,5,6],[7,8,9]])
determinante = np.linalg.det(matriz)
print(determinante)
print(determinante.round(5))

-9.51619735392994e-16
-0.0


**Ejercicio 2**

Construir una función en Python que les permita calcular una determinante 

### 4.4. Inversa de una Matriz

$$\mathbf{A} \cdot \mathbf{A}^{-1} = \mathbf{I}$$

In [61]:
matriz = np.array([[1, 2], [3, 4]])
inversa = np.linalg.inv(matriz)
print(matriz)

print(inversa)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


### 4.5. Valores y Vectores Propios

Para una matriz cuadrada $A$, un valor propio (o eigenvalor) $\lambda$ (lambda) y su correspondiente vector propio (o eigenvector) $\mathbf{v}$ no nulo satisfacen la ecuación:

$$A\mathbf{v} = \lambda\mathbf{v}$$

En otras palabras, cuando la matriz $A$ se aplica al vector $\mathbf{v}$, el resultado es el mismo vector multiplicado por un escalar $\lambda$.

In [75]:
matriz = np.array([[1, 2], [3, 4]])
valores_propios, vectores_propios = np.linalg.eig(matriz)
print("valores propios : {0}\n vectores propios: {1} ".format(valores_propios, vectores_propios ))

valores propios : [-0.37228132  5.37228132]
 vectores propios: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]] 


**Interpretación Geométrica**
Los vectores propios representan direcciones en las que la transformación lineal asociada a la matriz $A$ actúa como una simple dilatación o contracción. El valor propio correspondiente indica la magnitud de esta dilatación o contracción.


### 4.6 Matriz identidad 3x3

**Definición**
La matriz identidad, denotada comúnmente como $I$ o $I_n$ (donde $n$ es el tamaño de la matriz), es una matriz cuadrada especial con unos (1) en la diagonal principal y ceros (0) en todas las demás posiciones.

In [20]:
I3 = np.eye(3)
print("Matriz Identidad 3x3:")
print(I3)

Matriz Identidad 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



## 5. Sistemas de Ecuaciones Lineales

Para resolver $\mathbf{A}\mathbf{x} = \mathbf{b}$:

In [76]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
solucion = np.linalg.solve(A, b)
print(solucion)

[2. 3.]


## 6. Descomposición en Valores Singulares (SVD)

**Definición:**
La Descomposición en Valores Singulares (SVD) es una factorización de una matriz real o compleja. Para una matriz $A$ de dimensiones $m \times n$, la SVD es una factorización de la forma:


$$\mathbf{A} = \mathbf{U}\mathbf{\Sigma}\mathbf{V}^T$$

donde:

- $U$ es una matriz ortogonal $m \times m$
- $\Sigma$ es una matriz diagonal rectangular $m \times n$ con números reales no negativos en la diagonal
- $V^T$ es la transpuesta de una matriz ortogonal $n \times n$

Los elementos diagonales de $\Sigma$ son conocidos como los valores singulares de $A$.

In [30]:
matriz = np.array([[1, 2], [3, 4], [5, 6]])
U, S, Vt = np.linalg.svd(matriz)
print("U: {}\n\n S: {}\n\n Vt: {} \n\n".format(U,S,Vt))

U: [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

 S: [9.52551809 0.51430058]

 Vt: [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]] 




**Aplicaciones:**

- **Compresión de Datos:** Reduciendo el número de valores singulares, se puede aproximar una matriz con menos información.
- **Reducción de Dimensionalidad:** Similar al Análisis de Componentes Principales (PCA), la SVD puede usarse para reducir la dimensionalidad de conjuntos de datos.
- **Sistemas de Recomendación:** En el filtrado colaborativo, la SVD se utiliza para descubrir características latentes en los datos de usuario-ítem.
- **Procesamiento de Señales:** Para eliminar ruido y compresión de señales.
- **Reconocimiento Facial:** En el análisis de imágenes faciales para extracción de características.
- **Recuperación de Información:** En la búsqueda semántica latente para mejorar la recuperación de documentos relevantes.
- **Genómica:** En el análisis de datos de expresión génica.

## 7. Normas

Para un vector $\mathbf{x}$:

$$\|\mathbf{x}\| = \sqrt{\sum_{i=1}^n |x_i|^2}$$

In [31]:
vector = np.array([3, 4])
norma_vector = np.linalg.norm(vector)
print(norma_vector)

5.0


## 8. Ejemplo Práctico

In [81]:
import numpy as np

# Sistema: 
#    2x + 3y = 8
#    4x -  y = 1

A = np.array([[2, 3], [4, -1]])
b = np.array([8, 1])

# Resolución
x = np.linalg.solve(A, b)
print(f"Solución: x = {x[0]:.4f}, y = {x[1]:.4f}")

Solución: x = 0.7857, y = 2.1429


In [83]:
# Verificación
verificacion = np.allclose(np.dot(A, x), b) # A x ~ b
print(f"Solución correcta: {verificacion}") 

Solución correcta: True


In [84]:
# Determinante y inversa
det_A = np.linalg.det(A)
A_inv = np.linalg.inv(A)
print(f"Determinante de A: {det_A:.2f}")
print("Inversa de A:")
print(A_inv)

Determinante de A: -14.00
Inversa de A:
[[ 0.07142857  0.21428571]
 [ 0.28571429 -0.14285714]]


In [85]:
# Verificar A * A^(-1) = I
I = np.eye(2)
verificacion_inv = np.allclose(np.dot(A, A_inv), I)
print(f"A * A^(-1) = I: {verificacion_inv}")

A * A^(-1) = I: True


## 9. Conclusión

NumPy y su módulo `linalg` ofrecen herramientas poderosas para álgebra lineal, facilitando cálculos complejos en física, ingeniería y ciencia de datos.