# Variables y tipos de datos en Python

En Python, las variables se declaran en el momento de su creación, asignándoles un valor inicial. Su alcance depende de dónde se definan:

1. **Variables locales:** Creadas dentro de una función, son visibles solo dentro de ella.
2. **Variables globales:** Definidas fuera de cualquier función, son accesibles en todo el módulo.
3. **Variables predefinidas:** Existen en módulos o paquetes específicos, como el número π (pi) en la librería NumPy.

Para eliminar una variable y liberar la memoria que ocupa, se utiliza el comando `del`.

Algunos módulos y paquetes en Python proporcionan variables predefinidas que representan constantes matemáticas, físicas u otros valores útiles. Estas variables están disponibles para su uso inmediato al importar el módulo correspondiente.

## Tipos de datos 

- **Enteros (int):** Números enteros sin decimales.
- **Flotantes (float):** Números con decimales.
- **Cadenas (str):** Texto encerrado en comillas.
- **Booleanos (bool):** Valores True o False.
- **Listas (list):** Colecciones ordenadas y modificables.
- **Tuplas (tuple):** Colecciones ordenadas e inmutables.
- **Diccionarios (dict):** Colecciones de pares clave-valor.
- **Conjuntos (set):** Colecciones no ordenadas de elementos únicos.
- **None:** Representa la ausencia de valor.
- **Complejos (complex):** Números complejos con parte real e imaginaria.


### Entero (int)
edad = 25

### Flotante (float)
altura = 1.75

### Cadena (str)
nombre = "Ana García"

### Booleano (bool)
es_estudiante = True

### Lista (list)
colores = ["rojo", "verde", "azul"]

### Tupla (tuple)
coordenadas = (40.7128, -74.0060)

### Diccionario (dict)
persona = {
    "nombre": "Juan",
    "edad": 30,
    "ciudad": "Madrid"
}

### Conjunto (set)
frutas = {"manzana", "banana", "naranja"}

### None
valor_nulo = None

### Complejo (complex)
numero_complejo = 3 + 4j


Los tipos de datos mas comunes son los flotantes y los enteros. La función nos permite consultar el tipo de variable que estamos utilisado. 

In [1]:
var1= 4
type(var1)

int

In [2]:
var2=4.6
type(var2)

float

Tambien podemos incorporar boolianos como True o False

In [ ]:
a= 'true'
print(type(a))

<class 'str'>


## Tipos de datos y estructuras principales de NumPy

### ndarray
Array multidimensional, estructura fundamental de NumPy

Ejemplo: `np.array([1, 2, 3, 4])`

### dtype
Define el tipo de datos en un array

Ejemplo: `np.array([1, 2, 3], dtype=np.float64)`

### Vectores
Arrays unidimensionales

Ejemplo: 

`np.array([1, 2, 3, 4, 5])`

### Matrices
Arrays bidimensionales

Ejemplo: 

`np.array([[1, 2], [3, 4]])`

### Tensores
Arrays de tres o más dimensiones

Ejemplo: `pn.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])`

### Masked Arrays

Arrays que pueden tener valores enmascarados

Ejemplo: 

`np.ma.array([1, 2, 3, 4], mask=[0, 1, 0, 1])`

### Structured Arrays
Arrays con estructuras de datos complejas

Ejemplo: 

`np.array([('Alice', 25), ('Bob', 30)], dtype=[('name', 'U10'), ('age', 'i4')])`


### Memmap
Arrays mapeados en memoria para trabajar con archivos grandes

Ejemplo: `np.memmap('archivo.dat', dtype='float32', mode='w+', shape=(3,4))`

### Broadcasting

Capacidad de operar entre arrays de diferentes formas

Ejemplo: 

`np.array([1, 2, 3]) + np.array([[1], [2], [3]])`

### ufuncs
Funciones universales para operaciones elemento a elemento

Ejemplo: 

`np.sin(np.array([0, np.pi/2, np.pi]))`

## Variables predefinidas en NumPy

### Constantes matemáticas
- `np.pi`: El número pi (3.141592...)
- `np.e`: El número de Euler (2.718281...)
- `np.inf`: Infinito positivo
- `np.nan`: Not a Number (NaN)

### Tipos de datos
- `np.int8`, `np.int16`, `np.int32`, `np.int64`: Enteros con diferentes tamaños
- `np.float16`, `np.float32`, `np.float64`: Números de punto flotante
- `np.complex64`, `np.complex128`: Números complejos

por ejemplo:

`np.int8` representa un tipo de dato entero de 8 bits con signo. Esto significa que:

- Rango: Puede almacenar valores enteros desde -128 hasta 127.
- Tamaño: Ocupa 1 byte (8 bits) de memoria.
- Signo: Incluye números positivos y negativos

```text
        np.int8 (8 bits)
         _________________________
        |   |   |   |   |   |   | |
        |_S_|_6_|_5_|_4_|_3_|_2_|1|0|
         MSB                    LSB

        S: Bit de signo (0 = positivo, 1 = negativo)
        6-0: Bits de valor (7 bits)

        Rango: -2^7 a 2^7 - 1
               -128 a 127

        Ejemplos:
          0 = 00000000
        127 = 01111111
         -1 = 11111111
        -128 = 10000000

```

**Explicación:**

- El bit más significativo (MSB) es el bit de signo.
- Los 7 bits restantes representan el valor absoluto.
- Usa complemento a dos para representación de números negativos.
- El rango va desde -128 (10000000 en binario) hasta 127 (01111111 en binario).



### Constantes booleanas
- `np.True_`: Verdadero (1)
- `np.False_`: Falso (0)

### Otras constantes útiles
- `np.euler_gamma`: Constante de Euler-Mascheroni
- `np.newaxis`: Usado para aumentar la dimensionalidad de arrays

### Funciones matemáticas como variables
- `np.sin`, `np.cos`, `np.tan`: Funciones trigonométricas
- `np.exp`, `np.log`, `np.sqrt`: Funciones exponencial, logarítmica y raíz cuadrada

In [8]:
import numpy as np
print(type(np.pi))
print(np.pi)

<class 'float'>
3.141592653589793


In [10]:
2**7


128

## Mascaras

In [2]:
import numpy as np
#import numpy.ma as ma

# Crear un masked array
data = np.ma.array([1, 2, 3, -999, 5], mask=[0, 0, 0, 1, 0])
# El valor -999 está enmascarado y será ignorado en operaciones

print(data.mean())  # Calcula la media ignorando el valor enmascarado

2.75


## Variables tipo complejo

In [3]:
a= 1+5.0j
type(a)

complex

## Variables tipo array en Numpy

In [4]:
np.ones((2,3),int, order='C')

array([[1, 1, 1],
       [1, 1, 1]])

In [5]:
np.ones((2,3),int, order='F')

array([[1, 1, 1],
       [1, 1, 1]])

### Explicación de order

    order='C' (C-Contiguous):
        Los datos se almacenan en la memoria de tal manera que las filas son contiguas. Esto significa que el array se almacena en el mismo orden que se almacenan las matrices en el lenguaje de programación C.
        Este es el orden por defecto.
        Ejemplo: Para un array 2D, los elementos de la misma fila se almacenan consecutivamente en memoria.

    order='F' (Fortran-Contiguous):
        Los datos se almacenan en memoria de tal manera que las columnas son contiguas. Esto es similar al orden de almacenamiento en el lenguaje Fortran.
        Ejemplo: Para un array 2D, los elementos de la misma columna se almacenan consecutivamente en memoria.

In [6]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [7]:
arr1=np.zeros((2,3),int)
print(arr1)
print(type(arr1))

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>


Resumen de  Data Types


Python maneja los siguinetes data types:

    Text Type     : 	str
    Numeric Types : 	int, float, complex
    Sequence Types: 	list, tuple, range
    Mapping Type  : 	dict
    Set Types     : 	set, frozenset
    Boolean Type  : 	bool
    Binary Types  : 	bytes, bytearray, memoryview


