## Variables y tipos de datos

Las variables se declaran al momento de su creación. Las variables creadas dentro de una función son visibles en la ella y **del** nos permite eliminarlas

Los tipos de datos mas comunes son los flotantes y los enteros

In [2]:
var1= 4
type(var1)

int

In [ ]:
var2=4.6
type(var2)

float

Tambien podemos incorporar boolianos como True o False

In [ ]:
a= 'true'
print(type(a))

<class 'str'>


Tambien existe variables que seon definicas previamente en cada modulo o paquete. Por ejemplo el número $\pi$ en la librería Numpy
  


In [7]:
import numpy as np
print(type(np.pi))
print(np.pi)

<class 'float'>
3.141592653589793


Variables tipo complejo

In [4]:
a= 1+5.0j
type(a)

complex

Variables tipo array en Numpy

In [11]:
np.ones((2,3),int, order='C')

array([[1, 1, 1],
       [1, 1, 1]])

In [12]:
np.ones((2,3),int, order='F')

array([[1, 1, 1],
       [1, 1, 1]])

In [9]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this arg

In [13]:
arr1=np.zeros((2,3),int)
print(arr1)
print(type(arr1))

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>


Resumen de  Data Types


Python maneja los siguinetes data types:

    Text Type     : 	str
    Numeric Types : 	int, float, complex
    Sequence Types: 	list, tuple, range
    Mapping Type  : 	dict
    Set Types     : 	set, frozenset
    Boolean Type  : 	bool
    Binary Types  : 	bytes, bytearray, memoryview


